//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Avance 2 PA.rc
//
#define ID_ListaCli                     9
#define ID_InicioSesion                 101
#define ID_Registro                     103
#define IDR_MENU1                       115
#define ID_miUsu                        116
#define ID_PrincipalMenu                118
#define ID_RegistroMenu                 120
#define ID_CancelarRM                   120
#define ID_listaUsuMenu                 122
#define ID_AC                           124
#define ID_AP                           128
#define ID_ListaProm                    130
#define ID_ACO                          134
#define ID_LCO                          136
#define ID_UsuInicio                    1004
#define ID_contraInicio                 1005
#define ID_BotonRegistro                1006
#define ID_usuRegistro                  1008
#define ID_ContraRegistro               1009
#define ID_OKInicio                     1012
#define ID_CancelarInicio               1013
#define ID_OKRegistro                   1014
#define ID_CancelarRegistro             1015
#define ID_foto                         1023
#define IDC_STATICPath                  1024
#define ID_BuscarFoto                   1025
#define ID_comercioLista                1026
#define ID_comercioRegistro             1028
#define ID_ComRegistro                  1048
#define ID_tipoUsuRegistro              1049
#define IDC_miUsuNomCompleto            1058
#define IDC_comercioMiUsu               1059
#define IDC_cambiarFoto                 1060
#define IDC_modificarUsu                1061
#define IDC_RegistrarMiUsu              1062
#define IDC_tipoMiUsu                   1063
#define IDC_usuMiUsu                    1064
#define IDC_tipoMiUsu2                  1065
#define IDC_regresarMU                  1066
#define ID_SalirMenu                    1068
#define IDC_UsuRM                       1069
#define IDC_ComRM                       1070
#define IDC_ContraRM                    1071
#define IDC_TipoRM                      1072
#define ID_OKRM                         1073
#define ID_RegresarLU                   1077
#define IDC_listBoxUsu                  1078
#define IDC_CorreoAC                    1080
#define IDC_LBUsuComercio               1081
#define IDC_ComAC                       1082
#define IDC_LBTipoUsu                   1083
#define ID_CancelarAC                   1084
#define IDC_RegresarLC                  1085
#define IDC_ListBoxCli                  1086
#define IDC_LB_CliCorreo                1087
#define IDC_NomPromAP                   1088
#define IDC_PorcAP                      1089
#define IDC_FechaProm                   1090
#define ID_RegistrarAP                  1092
#define ID_CancelarAP                   1093
#define IDC_ListPromNom                 1096
#define IDC_RegresarLP                  1097
#define ID_RegistrarACO                 1098
#define ID_CancelarACO                  1099
#define IDC_CliNomACO                   1100
#define IDC_MontoACO                    1101
#define IDC_FechaACO                    1102
#define IDC_DescuentoACO                1103
#define IDC_SubTotalACO                 1104
#define IDC_TotalACO                    1105
#define IDC_LBConsFecha                 1106
#define IDC_LBConsSubTotal              1107
#define IDC_LBConsDesc                  1108
#define IDC_LBConsTotal                 1109
#define IDC_contraMiUsu                 1110
#define IDC_ComercioUsu                 1116
#define IDC_EDIT1                       1117
#define IDC_EDIT2                       1118
#define IDC_ComUsuReg                   1119
#define IDC_EDIT3                       1169
#define IDC_EliminarUsu                 1168
#define IDC_PorcLP                      1167
#define IDC_SubLC                       1120
#define IDC_EstatusProm                 1121
#define IDC_FechaLP                     1166
#define IDC_TotaLC                      1165
#define IDC_LBConsMonto                 1122
#define IDC_NomLP                       1164
#define IDC_EDIT6                       1163
#define IDC_LBCliFecha                  1123
#define IDC_MontoLP                     1162
#define IDC_RegresarLCO                 1124
#define IDC_ModificarProm               1161
#define IDC_ListNomCons                 1125
#define IDC_EliminarProm                1160
#define IDC_LBPromPD                    1126
#define IDC_clienteLC                   1159
#define IDC_LBPromMonto                 1127
#define IDC_MontoLC                     1158
#define IDC_LBPromFecha                 1128
#define IDC_DescLC                      1157
#define IDC_LBPromEstatus               1129
#define IDC_FechaLCO                    1156
#define IDC_LBCliComercio               1130
#define IDC_MontoAP                     1131
#define ID_RegistrarAC                  1132
#define IDC_Fecha                       1133
#define IDC_LBNomComp                   1134
#define IDC_NomAC                       1135
#define IDC_ComercioProm                1155
#define ID_PrincipalLista               1136
#define IDC_ComercioLP                  1154
#define IDC_COMBO1                      1137
#define IDC_comLC                       1153
#define IDC_EstatusLP                   1152
#define IDC_EstatusAP                   1151
#define IDC_ComercioACO                 1137
#define IDC_ComercioLCO                 1150
#define IDC_NomLC                       1149
#define IDC_LIST1                       1138
#define IDC_correoLC                    1139
#define IDC_FechaLC                     1140
#define IDC_ModificarCli                1141
#define IDC_EliminarCli                 1142
#define IDC_EDIT4                       1143
#define ID_ModificarContra              1148
#define IDC_contraMC                    1144
#define IDC_NomUsuMC                    1145
#define IDC_ModificarMC                 1146
#define ID_RegresarMC                   1147
#define ID_USUARIOS_MICUENTA            40007
#define ID_USUARIOS_ALTA                40008
#define ID_USUARIOS_LISTA               40009
#define ID_CLIENTES                     40010
#define ID_PROMOCIONES                  40011
#define ID_CONSUMOS                     40012
#define ID_CLIENTES_ALTA                40013
#define ID_CLIENTES_LISTA               40014
#define ID_CONSUMOS_ALTA                40015
#define ID_CONSUMOS_LISTA               40016
#define ID_PROMOCIONES_ALTA             40017
#define ID_PROMOCIONES_LISTA            40018
#define ID_USUARIOS_MODIFICARCONTRASENA 40019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         40020
#define _APS_NEXT_CONTROL_VALUE         1139
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
